### ISSUE TITLE
Waiting for CouchDB [---*--] FAILED

### ISSUE THREAD

**Issue by PDXIII** [hoodiehq/hood.ie#315]
Hello, I just wanted to try out Hood.ie but I can’t get it running. After I type in `hoodie start` it tries to connect to CouchDB, but this ends with a timeout. 

Fun fact: I can connect with CouchDB via Futon.

What do I missing?
I am on a Macbook Pro running El Capitan.
This is what the console says:

```
    ERR! Error: Timed out waiting for CouchDB. These logs may help:
    ERR!    /Users/pse/Seafile/Design - Open Files/Projects/_Product/_pse/CODE/hoodie-app/data/couch.stderr
    ERR!    /Users/pse/Seafile/Design - Open Files/Projects/_Product/_pse/CODE/hoodie-app/data/couch.stdout
    ERR!    /Users/pse/Seafile/Design - Open Files/Projects/_Product/_pse/CODE/hoodie-app/data/couch.log
    ERR!     at Request._callback (/Users/pse/Seafile/Design - Open Files/Projects/_Product/_pse/CODE/hoodie-app/node_modules/hoodie-server/lib/couchdb/index.js
    :145:27)
    ERR!     at self.callback (/Users/pse/Seafile/Design - Open Files/Projects/_Product/_pse/CODE/hoodie-app/node_modules/hoodie-server/node_modules/request/req
    uest.js:197:22)
    ERR!     at emitOne (events.js:96:13)
    ERR!     at Request.emit (events.js:188:7)
    ERR!     at Request.onRequestError (/Users/pse/Seafile/Design - Open Files/Projects/_Product/_pse/CODE/hoodie-app/node_modules/hoodie-server/node_modules/re
    quest/request.js:854:8)
    ERR!     at emitOne (events.js:96:13)
    ERR!     at ClientRequest.emit (events.js:188:7)
    ERR!     at Socket.socketErrorListener (_http_client.js:308:9)

    ERR!     at emitOne (events.js:96:13)
    ERR!     at Socket.emit (events.js:188:7)


    Stopping CouchDB...
```

And this is written in couch.stdout

```
    Apache CouchDB has started, time to relax.
    Apache CouchDB is running as process 11211, time to relax.
    Apache CouchDB is not running.
    Apache CouchDB is running as process 11211, time to relax.
    Apache CouchDB is not running.
    Apache CouchDB is running as process 11211, time to relax.
    Apache CouchDB is not running.
    Apache CouchDB is running as process 11211, time to relax.
    Apache CouchDB is not running.
    Apache CouchDB has started, time to relax.
    Apache CouchDB is running as process 606, time to relax.
    Apache CouchDB is not running.
    Apache CouchDB has started, time to relax.
    Apache CouchDB is running as process 836, time to relax.
    Apache CouchDB failed to shutdown.
```

Thank you for your attention!

**Comment by PDXIII** [comment]
Okay! I installed it in another directory and it runs. But what causes the error? Is it because SEAFILE is a cloud service?

**Comment by gr2m** [comment]
I’m just guessing, but maybe it has something to do with the spaces in the path? `Design - Open Files`

By the way it looks like you are using the old Hoodie version, but we have a new one just around the corner. It’s a bit confusing during the transition time as both are mentioned on our website. You can check out the new version at https://github.com/hoodiehq/hoodie and and example app using it is at https://github.com/hoodiehq/hoodie-app-tracker

You might need to uninstall the old version first with `npm uninstall --global hoodie`

**Comment by gr2m** [comment]
I’m closing the issue due to inactivity, please let me know if you have any further questions
